# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
#java-1.8.0-openjdk unzip telnet vim net-tools lsof git maven yum-utils device-mapper-persistent-data lvm2 docker-ce

$script = <<SCRIPT
  apt-get update; 
  apt-get --assume-yes install python-software-properties  software-properties-common apt-transport-https ca-certificates curl gnupg2 software-properties-common 
  curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg | sudo apt-key add -
  apt-key fingerprint 0EBFCD88
  add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") $(lsb_release -cs) stable"
  apt-get update
  
  apt-get --assume-yes install  unzip telnet vim net-tools lsof git maven thin-provisioning-tools lvm2 docker-ce

  apt-get --assume-yes install -t jessie-backports ca-certificates-java
  apt-get --assume-yes install openjdk-8-jdk
  update-java-alternatives --set java-1.8.0-openjdk-amd64
    
  systemctl start docker
  systemctl enable docker
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # copied directly from vagrant init chef/centos-6.5
  config.vm.box = "google/gce"
  
  config.vm.box_check_update = false
  config.vbguest.auto_update = false
  
  # workaround the vagrant 1.8.5 bug
  config.ssh.insert_key = false

  # change memory size
  # config.vm.provider "google" do |v|
    # v.memory = 4000
    # v.customize ['modifyvm', :id, '--memory', '2048', '--cpus', '1', '--cableconnected1', 'on']
    #v.name = "microservice-builder-base"
  #end


  config.vm.provider :google do |google, override|
	  google.google_project_id = "theta-index-158101"
	  google.google_client_email = "jeffzaza-api@theta-index-158101.iam.gserviceaccount.com"
	  google.google_json_key_location = "/home/jeffzazajr/workspace/ICP_Local_Install/vagrant/microservice-builder-base/jeffzaza-api.json"

    	  google.name = "microservice-builder-base"
	  google.disk_size= "20"
	  google.zone = "asia-east1-a"	  

          override.ssh.username = "jeffzazajr"
	  override.ssh.private_key_path = "/home/jeffzazajr/workspace/ICP_Local_Install/vagrant/microservice-builder-base/jeff-local-ubuntu-ssh-key"
	  #override.ssh.private_key_path = "~/.ssh/google_compute_engine"
  end


  # config.vm.boot_timeout = 600
  # Oracle port forwarding
  # config.vm.network "forwarded_port", guest: 1521, host: 1521
  #config.vm.network "public_network", bridge: "en5: Thunderbolt Ethernet", use_dhcp_assigned_default_route: true
  #config.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", use_dhcp_assigned_default_route: true
  #config.vm.network "public_network", bridge: "en7: iPhone USB", use_dhcp_assigned_default_route: true
  
  config.vm.network "public_network"
  config.vm.provision "shell", inline: $script

  # Provision everything on the first run
  # config.vm.provision "shell", path: "scripts/install.sh"

  # if Vagrant.has_plugin?("vagrant-proxyconf")
  #   config.proxy.http     = "http://proxy.example.com/"
  #   config.proxy.https    = "http://proxy.example.com/"
  #   config.proxy.no_proxy = "localhost,127.0.0.1"
  # end

end