# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

$script = <<SCRIPT
  apt-get update; 
  apt-get --assume-yes install python-software-properties  software-properties-common 
  add-apt-repository   "deb [arch=amd64] https://download.docker.com/linux/debian   $(lsb_release -cs)  stable"
  add-apt-repository   "deb http://http.debian.net/debian jessie-backports main"
          
  apt-get --assume-yes install -t jessie-backports openjdk-8-jre-headless
  apt-get --assume-yes install openjdk-8-jdk
              
  apt-get --assume-yes install  unzip telnet vim net-tools lsof git maven thin-provisioning-tools lvm2 docker-ce
  systemctl start docker
  systemctl enable docker

  
  apt-get --assume-yes install wget

  apt-get --assume-yes install jq
  cd ~/ && curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl


  hostnamectl set-hostname proxy-node
  mkdir -p /etc/systemd/system/docker.service.d && \
  touch /etc/systemd/system/docker.service.d/override.conf && \
  echo '[Service]' > /etc/systemd/system/docker.service.d/override.conf && \
  echo 'ExecStart=' >> /etc/systemd/system/docker.service.d/override.conf && \
  echo 'ExecStart=/usr/bin/dockerd --insecure-registry=boot-node:5000' >> /etc/systemd/system/docker.service.d/override.conf && \
  systemctl daemon-reload && \
  systemctl restart docker
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # copied directly from vagrant init chef/centos-6.5
  config.vm.box = "google/gce"

  config.vm.box_check_update = false
  config.vbguest.auto_update = false

  # workaround the vagrant 1.8.5 bug
  config.ssh.insert_key = false

  # change memory size
  # config.vm.provider "google" do |v|
    # v.memory = 4000
    # v.customize ['modifyvm', :id, '--memory', '2048', '--cpus', '1', '--cableconnected1', 'on']
    #v.name = "microservice-builder-base"
  #end

  config.vm.provider :google do |google, override|
          google.google_project_id = "theta-index-158101"
          google.google_client_email = "jeffzaza-api@theta-index-158101.iam.gserviceaccount.com"
          google.google_json_key_location = "/home/jeffzazajr/workspace/ICP_Local_Install/vagrant/microservice-builder-base/jeffzaza-private-key.json"

          google.name = "proxy-node"
          google.image = "jeff-microservice-builder-image"

          override.ssh.username = "jeffzazajr"
          override.ssh.private_key_path = "/home/jeffzazajr/workspace/ICP_Local_Install/vagrant/microservice-builder-base/jeff-local-ubuntu-ssh-key"
          #override.ssh.private_key_path = "~/.ssh/google_compute_engine"
  end

  # config.vm.boot_timeout = 600
  # Oracle port forwarding
  # config.vm.network "forwarded_port", guest: 1521, host: 1521
  #config.vm.network "public_network", bridge: "en5: Thunderbolt Ethernet", use_dhcp_assigned_default_route: true
  #config.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", use_dhcp_assigned_default_route: true
  #config.vm.network "public_network", bridge: "en7: iPhone USB", use_dhcp_assigned_default_route: true

  config.vm.network "public_network"
  config.vm.provision "shell", inline: $script

  # Provision everything on the first run
  # config.vm.provision "shell", path: "scripts/install.sh"

  # if Vagrant.has_plugin?("vagrant-proxyconf")
  #   config.proxy.http     = "http://proxy.example.com/"
  #   config.proxy.https    = "http://proxy.example.com/"
  #   config.proxy.no_proxy = "localhost,127.0.0.1"
  #   end

end




